# Generated by Django 4.2.3 on 2023-08-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feane', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_type',
            field=models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('pasta', 'Pasta'), ('fries', 'Fries')], default='', max_length=200),
        ),
    ]
