# Generated by Django 4.2.3 on 2023-08-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feane', '0002_product_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
