# Generated by Django 4.2.3 on 2023-08-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feane', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=0, default='0.00', max_digits=5),
        ),
    ]
