# Generated by Django 4.2.3 on 2023-08-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feane', '0006_alter_posts_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
