# Generated by Django 4.2.3 on 2023-08-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feane', '0008_alter_posts_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
